#index:
#    path: /
#    controller: App\Controller\DefaultController::index

questions:
  path: /questions
  controller: App\Controller\QuestionsController::index

AssignExamToStudentController:
  path: /exam
  controller: App\Controller\AssignExamToStudentController::index

exams:
path: /exam
controller: App\Controller\ExamsController::index

AssignQuestionToExamController:
path: /questions
controller: App\Controller\AssignQuestionToExam::index